services:
  frontend:
    build:
      context: ./Frontend
    restart: always

  backend:
    build:
      context: ./backend
      ports:
        - "8080:8080"
    restart: always

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/archive/controlling.xaidemo.de/:/letsencrypt/:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    restart: always
    #- "8080:8080"
