services:
  frontend:
    build:
      context: ./Frontend
    restart: always

  backend:
    build:
      context: ./Backend
    ports:
     - "8080:8080"
    restart: always
    depends_on:
      - couchdb
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: password

  couchdb:
    build:
      context: ./CouchDB
      dockerfile: Dockerfile # Path to your CouchDB Dockerfile
    ports:
      - "5984:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=password
    restart: always


  nginx:
  image: nginx:alpine
  user: root  # Fügen Sie diese Zeile hinzu
  volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    - /etc/letsencrypt/archive/controlling.xaidemo.de/:/letsencrypt/:ro
    - /etc/letsencrypt/live/controlling.xaidemo.de/:/etc/letsencrypt/live/controlling.xaidemo.de/:ro
  ports:
    - "80:80"
    - "443:443"
  depends_on:
    - frontend
    - backend
  restart: always
volumes:
  couchdb_data:
