name: Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
      runs-on: ubuntu-latest

      steps:
        - name:
            Pull Repository from Github
          uses: appleboy/ssh-action@v0.1.5
          with:
            host: ${{ secrets.HOST }}
            username: ${{ secrets.USER }}
            key: ${{ secrets.KEY }}
            script: |
              cd XAI-im-Controlling
              git pull
              sudo docker-compose down
              sudo -E docker-compose up --build -d